# Generated by Django 4.1.1 on 2023-04-22 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_id", models.CharField(default="010203", max_length=20)),
                ("x_axis", models.CharField(default="x-axis", max_length=250)),
                ("y_axis", models.CharField(default="y-axis", max_length=250)),
                ("z_axis", models.CharField(default="z-axis", max_length=200)),
                (
                    "machine_speed",
                    models.CharField(default="machine_speed", max_length=200),
                ),
                ("angle", models.CharField(default="angle", max_length=200)),
                (
                    "in_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "machine_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.machine"
                    ),
                ),
            ],
            options={
                "db_table": "instruction",
            },
        ),
    ]
