# Generated by Django 4.1.3 on 2023-01-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert_chat',
            name='machine_id',
        ),
        migrations.AddField(
            model_name='expert_chat',
            name='req_id',
            field=models.CharField(default='0102', max_length=20),
        ),
    ]
