# Generated by Django 4.1.1 on 2023-04-22 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Serviceman_chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("req_id", models.CharField(default="0102", max_length=20)),
                ("message", models.TextField(default="Description Message")),
                (
                    "chat_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "serviceman_chat",
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("req_id", models.CharField(default="0102", max_length=20)),
                ("message", models.TextField(default="Description Message")),
                (
                    "chat_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "chat",
            },
        ),
    ]
