# Generated by Django 4.1.3 on 2022-11-15 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(default='0102', max_length=20)),
                ('image', models.ImageField(upload_to='requests/')),
            ],
            options={
                'db_table': 'requestimage',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(default='010203', max_length=20)),
                ('subject', models.CharField(default='subject', max_length=250)),
                ('request_status', models.CharField(default='Pending', max_length=250)),
                ('request_type', models.CharField(default='Maintainance', max_length=200)),
                ('description', models.TextField(default='Description Body')),
                ('req_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.machine')),
            ],
            options={
                'db_table': 'request',
            },
        ),
    ]
