# Generated by Django 4.1.1 on 2023-04-22 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_name", models.CharField(max_length=200)),
                ("machine_code", models.CharField(default="", max_length=350)),
                ("machine_picture", models.ImageField(null=True, upload_to="machine/")),
                ("machine_type", models.CharField(default="Machine", max_length=100)),
                ("machine_status", models.CharField(default="Status", max_length=100)),
            ],
            options={
                "db_table": "machine",
            },
        ),
        migrations.CreateModel(
            name="RequestImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("req_id", models.CharField(default="0102", max_length=20)),
                ("image", models.ImageField(upload_to="requests/")),
            ],
            options={
                "db_table": "requestimage",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="First Name", max_length=200)),
                ("last_name", models.CharField(default="Last Name", max_length=200)),
                ("user_picture", models.ImageField(null=True, upload_to="profile/")),
                ("phone", models.CharField(default="Phone", max_length=200)),
                ("email", models.CharField(default="email", max_length=250)),
                (
                    "user_category",
                    models.CharField(default="user category", max_length=250),
                ),
                ("password", models.CharField(default="null", max_length=200)),
                (
                    "user_status",
                    models.CharField(default="Account Status", max_length=100),
                ),
                (
                    "reg_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("req_id", models.CharField(default="010203", max_length=20)),
                ("subject", models.CharField(default="subject", max_length=250)),
                ("request_status", models.CharField(default="Pending", max_length=250)),
                (
                    "request_type",
                    models.CharField(default="Assistance", max_length=200),
                ),
                ("description", models.TextField(default="Description Body")),
                (
                    "req_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("worker_status", models.CharField(default="Pending", max_length=250)),
                ("expert_status", models.CharField(default="Pending", max_length=250)),
                (
                    "serviceman_status",
                    models.CharField(default="Pending", max_length=250),
                ),
                ("request_sender", models.CharField(default="Worker", max_length=50)),
                ("worker_view", models.IntegerField(default="0")),
                ("expert_view", models.IntegerField(default="0")),
                ("serviceman_view", models.IntegerField(default="0")),
                (
                    "machine_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.machine"
                    ),
                ),
            ],
            options={
                "db_table": "request",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request", models.CharField(default="Request", max_length=200)),
                ("title", models.CharField(default="title", max_length=350)),
                ("description", models.TextField(default="Description")),
                ("not_sender", models.CharField(default="Worker", max_length=50)),
                ("not_status", models.CharField(default="Status", max_length=100)),
                (
                    "not_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "machine_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.machine"
                    ),
                ),
                (
                    "not_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.requests"
                    ),
                ),
            ],
            options={
                "db_table": "notification",
            },
        ),
        migrations.AddField(
            model_name="machine",
            name="machine_expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="m_experts",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="machine_serviceman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="m_serviceman",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="machine_worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="m_users",
                to="user.user",
            ),
        ),
    ]
