# Generated by Django 4.1.3 on 2022-11-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_serviceman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='m_serviceman', to='user.user'),
            preserve_default=False,
        ),
    ]
