# Generated by Django 4.1.3 on 2022-12-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='not_sender',
            field=models.CharField(default='Worker', max_length=50),
        ),
    ]
