# Generated by Django 4.1.3 on 2022-12-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_notification_not_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='expert_view',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='serviceman_view',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='worker_view',
            field=models.IntegerField(default='0'),
        ),
    ]
